project 'deepRed.xcodeproj/'

platform :ios, '12.0'

target 'deepRed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.3'


  target 'deepRedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'deepRedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
